apiVersion: serving.knative.dev/v1alpha1
kind: DomainMapping
metadata:
  name: helloworld-go.default.172.18.255.200.sslip.io
  namespace: default
spec:
  ref:
    name: helloworld-go
    kind: Service
    apiVersion: serving.knative.dev/v1
  tls:
    secretName: tls-secret
