apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: target
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/target: "1"
    spec:
      containers:
      - image: quay.io/rlehmann/runtime
