apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: runtime
  namespace: default
  labels:
    networking.knative.dev/visibility: 'cluster-local'
spec:
  template:
    spec:
      containers:
      - image: quay.io/rlehmann/runtime
