apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: runtime
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
      - image: quay.io/rlehmann/runtime
        readinessProbe:
          httpGet:
            port: 8080 # this will be called by QP, not K8s
